# Generated by Django 4.1.7 on 2024-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_marks',
            field=models.TextField(default='{}'),
        ),
    ]
