# Generated by Django 4.1.7 on 2024-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subTeacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STLogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
